---
language: node_js
node_js:
  - "10"

branches:
  only:
    - master
    - redesign-rfc

addons:
  chrome: stable

before_install:
  - npm install -g @lhci/cli@0.5.x

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master

script:
  - npm run lint
  - npm run test
  - npm run build
  - lhci autorun
