---
language: node_js
node_js:
  - "8"

sudo: false
dist: trusty

branches:
  only:
    - master

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - yarn install --non-interactive

script:
  - yarn lint:hbs
  - yarn lint:style
  - yarn lint:js
  - yarn test
  - yarn build --environment production
