---
language: node_js
node_js:
  - "8"

sudo: false
dist: trusty

branches:
  only:
    - master

addons:
  chrome: stable

cache:
  npm: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm install

script:
  - npm lint:hbs
  - npm lint:style
  - npm lint:js
  - npm test
  - npm build --environment production
